name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # 👉 можно запускать вручную

jobs:
  test-and-log-check:
    runs-on: ubuntu-latest

    env:
      AGE: 25  # 👉 используем ENV вместо echo

    steps:
      - name: Кодду көчүрүү
        uses: actions/checkout@v4

      - name: Python орнотуу
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Pip жаңыртуу
        run: python -m pip install --upgrade pip

      - name: Тесттерди иштетүү
        run: python test_logic.py

      - name: Программаны иштетүү
        run: python main.py

      - name: Лог файлды текшерүү
        run: |
          if [ -f app.log ]; then
            echo "Лог файлы түзүлдү!"
          else
            echo "Лог файл табылган жок!"
            exit 1
          fi

